version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "pushnotificationsdk/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "pushnotificationsdk/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew :pushnotificationsdk:lint :pushnotificationsdk:test
      - run:
          name: Run Build
          command: ./gradlew :pushnotificationsdk:build
      - store_artifacts:
          path: pushnotificationsdk/build/reports
          destination: reports
      - store_test_results:
          path: pushnotificationsdk/build/test-results
      - store_artifacts:
          path: pushnotificationsdk/build/outputs/aar
          destination: aar_artifacts